# Heroku Container Registry Configuration
# https://devcenter.heroku.com/articles/build-docker-images-heroku-yml
build:
  docker:
    web: Dockerfile
run:
  web: /app/parse-dmarc --config=/app/config.json
